# Generated by Django 3.0.5 on 2020-05-02 12:19

import api
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videourl', models.CharField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_save_name', models.FileField(upload_to=api.file_upload_path_for_db)),
                ('file_origin_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
            ],
        ),
    ]
