# Generated by Django 3.0.5 on 2020-05-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='threshold',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
